# Generated by Django 3.2.7 on 2022-02-18 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ_Course',
            fields=[
                ('course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option', models.CharField(max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Test',
            fields=[
                ('test_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_app.mcq_course')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_TestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1)),
                ('marks_obtained', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.mcq_question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.mcq_student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.mcq_test')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Teaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incharge', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.mcq_course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.mcq_teacher')),
            ],
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_app.mcq_test'),
        ),
    ]
