# Generated by Django 3.2.7 on 2022-02-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_test',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
